### ISSUE TITLE
Not following repository naming convention

### ISSUE THREAD

**Issue by axeltaylor** [ERNI-Academy/assets-cosmosdb-rediscache-docker-compose#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This respository is not following [the naming convention](https://github.com/ERNI-Academy/awesome-resources/blob/main/CONTRIBUTING.md#2-how-to-create-a-resource).

### Expected Behavior

Change asset**s**-cosmosdb-rediscache-docker-compose for **asset**-cosmosdb-rediscache-docker-compose.

### Steps To Reproduce

N/A

### Exceptions (if any)

N/A

### Anything else?

N/A

**Comment by Rabosa616** [comment]
Done
